### ISSUE TITLE
Add OAuth/OAuth2 options to ICRemoteConfiguration

### ISSUE THREAD

**Issue by sdgandhi** [khanlou/InstantCocoa#1]
OAuth2 is a popular and secure way to consume APIs without storing usernames and passwords. Many APIs use this authentication method. InstantCocoa would benefit from incorporating this functionality.

**Comment by khanlou** [comment]
Agreed, and it's something I definitely would like to support, but it's not clear exactly how it should be a part of `ICRemoteConfiguration`. If you have a proposal, I would definitely be down to hear it.

**Comment by kaandedeoglu** [comment]
Why not just have a `OAuth2Token` property and do `setValue:forHTTPHeaderField` with Value being: "Bearer {OAuth2Token}" and  HeaderField being "Authorization"
